/**
 * AG-UI Protocol Definition (Frontend Adaptation)
 * Defines the structure of UI components generated by the AI.
 */

export enum ComponentType {
  MARKDOWN = 'markdown',
  INFO_CARD = 'info_card',
  DATA_LIST = 'data_list',
  STEP_PROCESS = 'step_process',
  TABLE = 'table'
}

export interface BaseComponent {
  type: ComponentType;
  id?: string;
}

export interface MarkdownComponent extends BaseComponent {
  type: ComponentType.MARKDOWN;
  content: string;
}

export interface InfoCardComponent extends BaseComponent {
  type: ComponentType.INFO_CARD;
  title: string;
  description: string;
  variant: 'info' | 'warning' | 'success' | 'danger';
}

export interface DataItem {
  label: string;
  value: string;
}

export interface DataListComponent extends BaseComponent {
  type: ComponentType.DATA_LIST;
  title?: string;
  items: DataItem[];
}

export interface StepItem {
  title: string;
  description: string;
}

export interface StepProcessComponent extends BaseComponent {
  type: ComponentType.STEP_PROCESS;
  // Added title property to match usage in AGUIRenderer
  title?: string;
  steps: StepItem[];
}

export interface TableComponent extends BaseComponent {
  type: ComponentType.TABLE;
  title?: string;
  headers: string[];
  rows: string[][];
}

export type AGUIComponent = 
  | MarkdownComponent 
  | InfoCardComponent 
  | DataListComponent
  | StepProcessComponent
  | TableComponent;

export interface AGUIResponse {
  components: AGUIComponent[];
  suggestions: string[]; // Next likely questions
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content?: string; // For user messages
  data?: AGUIResponse; // For model messages (Structured AG-UI)
  timestamp: number;
}